folio-org/stripes

- README.md
> Update links to moved docs

- doc/i18n.md
> Update i18n with Lokalise information

- CHANGELOG.md
The release notes included the headline from the v2.3.0 release.
> fix v2.4.0 release notes

- doc/i18n.md
- doc/release-procedure.md
Link to new "Add to platforms" section of main release guidelines.
[FOLIO-1963](https://issues.folio.org/browse/FOLIO-1963)
> FOLIO-1963 doc release procedures platforms

- Jenkinsfile
Adds duplicate dependency check described in https://issues.folio.org/browse/FOLIO-1790
> adds stripes-* duplicate dep check

- package.json
bumping the dep on stripes-smart-components, so bumping the minor here too.
> bump SSC minor in prep for next release

- doc/dev-guide.md
Documentation for https://github.com/folio-org/stripes-core/pull/684/
> Allow modules to be of more than one type. (STCOR-148)

- CHANGELOG.md
- final-form/index.js
- package.json
@zburke I created a new PR for 2.9.0
> Release v2.9.0

- doc/dev-guide.md
* `welcomeMessage`
* `platformName` and `platformDescription` (STCOR-385, STCOR-386)
> Document recent stripes-config additions

- doc/release-procedure.md
Refs [STCOR-393](https://issues.folio.org/browse/STCOR-393)
> STCOR-393 warn about the 'latest' dist-tag in 'npm publish'

- doc/dev-guide.md
As requested in ReShare issues PR-479.
https://openlibraryenvironment.atlassian.net/browse/PR-479
This is currently implemented by ui-rs.
> Add showPerms documentation

- doc/dev-guide.md
Documentation for i18n support added in https://github.com/folio-org/ui-users/pull/1240
> Documented i18n of permissionSets

- doc/dev-guide.md
I wasn't super clear whether the array was just strings or objects and the format, so I added it.
> Add example of stripesDeps

- doc/release-procedure.md
It was pointed out to me that we don't have good documentation about how to prepare a patch release.
> better patch release doc

- doc/custom-fields.md
This documents the usage and rationale behind the `useCustomFields` hook https://github.com/folio-org/stripes-core/pull/1031
> Added doc about Custom Fields

- README.md
No change to code or substance of documentation
> Update README copyright date to current year

- package.json
No feature work was planned initially, but some has since been
scheduled so we are bumping the version accordingly.
> bump stripes-connect to 7.1

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
Build with Node 16 in CI.
Refs [STRIPES-802](https://issues.folio.org/browse/STRIPES-802)
> STRIPES-802 build with Node v16 in CI

- doc/dev-guide.md
> Clarify team responsibility for upgrading dependencies

- doc/branding.md
Explain how to customize the `<Login>` component's wrapper-div CSS and the navigation bar's CSS via values provided in `stripes.config.js` via `branding.style`.
> STCOR-643, STCOR-644: Customization of mainNav and login CSS

- package.json
Bump stripes-connect version to `~8.2.0`
> Bump stripes-connect version

- package.json
This reverts commit 15caf7178e2acceaf781c930901597acdf7e8599.
> Revert "Bump stripes-connect version (#205)"

- doc/new-development-setup.md
A temporary footnote.  https://folio-project.slack.com/archives/C210UCHQ9/p1666958210750469?thread_ts=1666920965.190759&cid=C210UCHQ9
> Note new-development-setup temp requires Node v16

- CHANGELOG.md
- package.json
Refs [STRIPES-891](https://issues.folio.org/browse/STRIPES-891), [FOLREL-584](https://issues.folio.org/browse/STRIPES-584)
> Release v9.0.0

- package.json
If you want to release v9.2.1, you _actually have to set the version to 9.2.1_. WHO KNEW?!?
> REALLY release v9.2.1

- CHANGELOG.md
- package.json
* `stripes-components` `12.2.9` https://github.com/folio-org/stripes-components/releases/tag/v12.2.9
> Release v9.2.12

- doc/release-procedure.md
Small doc update for our poor aged memories...
> Add "set fix version" bullets for release procedure.
