folio-org/stripes

README.md, doc/stripes-framework.md
This as a brief introduction to the stripes framework.  Included is a migration guide to assist any developers with apps hosted outside of FOLIO's Github repos that have not migrated to stripes v1 yet.
=> STRIPES-569 stripes overview

README.md
This adds links to Stripes docs in their existing locations and attempts to organize them in the process.  Doing so enables the Stripes repo to act as an entry point for front-end documentation.
Next steps:
* Move select documents from stripes-core into this repo and update readme links (separate PR)
* Update links from dev.folio.org
* Pin stripes and unpin stripes-core repos on folio-org
=> STRIPES-573 prep for moving docs

doc/i18n.md
Tests related to dates were found to be failing for some people in other timezones. Upon investigating they were rightfully failing because UTC dates were incorrectly being formatted as local dates. This was happening because `moment()` assumes values to be local time when there is no timezone information. So dates such as `12/01` were being formatted as `11/30` when viewed in timezones east of UTC.
Related: [STCOR-265](https://issues.folio.org/browse/STCOR-265)
Working with dates can be a nightmare. When comparing or manipulating dates, it is safest to always work in UTC and let internationalization helpers handle formatting the display for local timezones. This PR adds a short description to the dates section of the i18n doc and links to `moment.utc()`.
=> Add moment.utc information to internationalization doc

doc/bigtest.md
Introduces a guide for getting started with BigTest in Stripes.
Related to the following BigTest documentation issues: 
- [[STRIPES-567] Document BigTest setup for UI modules: Mirage documentation](https://issues.folio.org/browse/STRIPES-567)
- [[STRIPES-574] Document BigTest setup for UI modules: Stripes CLI and stripes-core helper documentation](https://issues.folio.org/browse/STRIPES-574)
- [[STRIPES-579] Create BigTest stripes interactors documentation](https://issues.folio.org/browse/STRIPES-579)
For the Mirage documentation, there is a plethora of information available on the official website. So rather than reiterate the same content, I outlined the subtle differences between `@bigtest/mirage` and the original `ember-cli-mirage` package and linked out to the original sources. I …
=> Add BigTest in Stripes documentation

doc/i18n.md
More helpful guidance for declarative localization - 
I've updated documentation with two items: 
- The often overlooked 'renderProps' usage of `<FormattedMessage>`
- The new approach to accessing the `intl` object via the `<IntlConsumer>` component
=> STRIPES-538 Add documentation for IntlConsumer

doc/stripes-framework.md
The release of individual `stripes-*` modules continue to follow the [Stripes release procedure](https://github.com/folio-org/stripes/blob/master/doc/release-procedure.md).  However, the framework itself has more moving parts to consider when it comes to rolling out a new release to ui-modules and platforms.  This aims to capture those extra steps giving us a checklist to follow the next time around.  I expect this to evolve as we learn from more frequent releases. Hopefully it helps to identify steps in need of refinement and those that can be automated.
Refs STRIPES-588
=> Stripes framework release procedure

CHANGELOG.md, package.json
New features in stripes dependencies mean we need to bump the minor
versions of everything in the stripes dependency chain.
=> bump stripes deps

doc/i18n.md
Previous documentation recommended `injectIntl` which uses React's
deprecated context API and is, in fact, no longer recommended. Added
examples of using `stripes-core`'s `<IntlConsumer>` to access `intl`
instead.
Refs [STCOR-189](https://issues.folio.org/browse/STCOR-189)
=> STCOR-189 better i18n doc WRT context

CHANGELOG.md, package.json
This is no different than v2.11.1 aside from an updated version number in the `package.json`, but since `yarn install` will first attempt to satisfy a dependency with the version labeled by the `dist-tag` `latest`, and _then_ satisfy additional (possibly more strict) dependencies by adding additional copies to the bundle, sometimes we get multiple copies of things we don't want multiple copies of. 
Wha? If you have dev deps on stripes and stripes-cli, which both have a dep on stripes-core, it's easy to get multiple copies of stripes-core in the bundle because those can conflict because we'll get a newish stripes-core from stripes-cli and an oldish one from that backported `latest` release.
=> Release v2.11.2

package.json
- Fulfills part of https://issues.folio.org/browse/STRIPES-648.
- Updated eslint-config-stripes to 5.0.0 which also contains updated version of eslint.
=> Updated eslint and eslint-config-stripes versions

doc/release-procedure.md
Usually it confuses people (and maybe Jenkins) that branch has the same name as the tag. Maybe we should change it here to use a different branch name.
=> More proper release branch name

package.json
`stripes-util` was inadvertenly omitted from the original round of PRs
updating stripes-* libraries in preparation for `@folio/stripes`
`v3.0.0`. This PR simply brings in that update.
=> bump stripes-util to v2

CHANGELOG.md, package.json
Release `v4.1.5` was tagged on a branch split from the `v4.1.4` tag on the `b4.1` branch rather than directly on `b4.1` itself (whoops, but NBD). This PR merges that release branch back into `b4.1` in order to provide continuity with future `v4.1.x` patch releases tagged directly on the `b4.1` branch.
=> merge 4.1.5 release-branch back into b4.1 for continuity

ROADMAP.md
`react` `v17` isn't actually a breaking change, but it paves the way to
simplify the adoption of breaking changes in `v18`. Hence, we should
adopt this as soon as possible in order to simplify the process of
future upgrades.
Refs [STRIPES-722](https://issues.folio.org/browse/STRIPES-722)
=> STRIPES-722 increment react to v17

ROADMAP.md
Increment to `react-redux` `v7`, `redux-form` `v8`, `redux` `v4`. We are
a major version behind in each of these, and the longer we wait the more
difficult it will be to update. It is particularly worth noting that the
`react-redux` `v7` release restores the APIs that were removed in `v6`,
and which had previously made this look like a substantial task. In
truth, it turned out to be nearly painless, as @doytch discovered when
he finally, ahem, actually tried this out while I was busy wringing my
hands about what a difficult path it would be to tread.
Incrementing `redux-form` to `v8` will also substantially reduce the
console noise we see in development (see [STCOR-353](https://issues.folio.org/browse/STCOR-353)).
Refs [STRIPES-721](https://issues.folio.org/browse/STRIPES-721)
=> STRIPES-721 increment redux-related dependencies

ROADMAP.md
Increment `rxjs` from `v5` to `v6`. This will require changes at least
in `stripes-core` and `stripes-connect` and probably other apps as well
(`ui-eholdings`).
If the version needs to be synced across all modules, the dependency
should be moved up to the platform level. If it only needs to be synced
across the stripes libraries, i.e. if apps' use is internal, I _think_
we would be fine supplying it to stripes-* via `@folio/stripes` but
we'll need to test that.
In either case, if we are changing a peer dependency, this work will
need to be part of a major release. Do we want to aim at Juniper here,
or should we push this out further? 
Refs [STRIPES-723](https://issues.folio.org/browse/STRIPES-723)
=> STRIPES-723 add RXJS upgrade to Juniper roadmap

ROADMAP.md
We're currently using `babel-eslint` which is old and doesn't work properly. It throws false positives for things like `for (const foo of bar)` loops in v8, and v10 has parsing bugs in our env. [Meanwhile, `@babel/eslint-parser` is out and is the replacement for babel-eslint.](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint)
We're seeing a bunch of cases where legitimate eslint errors are getting merged into code because the list of eslint errors is so large that it's being ignored in PRs. This needs to get done to clean up a bunch of the false positives so that we can attack the stuff that's currently just being ignored by everyone like linter errors related to React hooks.
=> Add @babel/eslint-parser upgrade to roadmap

ROADMAP.md
As cataloged at [STRIPES-722](https://issues.folio.org/browse/STRIPES-722) and [STCOR-504](https://issues.folio.org/browse/STCOR-504), there are aspects of the
`react` `v17` upgrade we did not anticipate and cannot resolve in time
to commit those changes for this release.
We still must plan to upgrade to `v17`, but now ain't the time.
Refs [STRIPES-722](https://issues.folio.org/browse/STRIPES-722)
=> STRIPES-722 move react v17 upgrade to next release

doc/release-procedure.md
Include details about updating the notes attached to the GitHub tag in
the release-procedure documentation.
Refs [STRIPES-587](https://issues.folio.org/browse/STRIPES-587)
=> STRIPES-587 update release documentation

ROADMAP.md
**Q: Huh? What's the point of this PR???**
A: This PR updates the `ROADMAP.md` file that we use to maintain an at-a-glance plan for Stripes development in the future. It doesn't _commit_ to the work, but it does represent the goal of Stripes' authors. This is the first of a series of "you've been warned" steps when planning breaking changes.
**Onto the specifics of this PR...**
Moving to NPM 7 would mean that building a Stripes bundle uses NPM 7 (and Node 15/16) instead of using `yarn`. This has implications on front-end devs and dev-ops.
The wins it gives us include:
- removing an entire category of difficult-to-debug errors that crop up when multiple versions of a library are imported because Yarn is bad at resolving compatible versions
- better error reporting
- not needing to define …
=> Add NPM7 migration to roadmap for Kiwi

doc/dev-guide.md
- Add section in dev guide on when major third-party dependencies should be updated at platform-level (aka peer dependency)  and when minor third-party dependencies should be updated at module level.
- Also updated list of `peerDependencies`
=> Create documentation for when to update stripes and external dependencies

doc/release-procedure.md
Per [this Slack thread](https://folio-project.slack.com/archives/C210UCHQ9/p1647283843670969), the build and release step should be skipped for GA-compatible modules.  This PR updates this language and a few other Jenkins-specific references throughout the release procedures doc.
=> Update Release Procedures for GA Workflows

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json
Build with Node 16, active LTS, in CI.
Refs [STRIPES-802](https://issues.folio.org/browse/STRIPES-802)
=> STRIPES-802 build with Node v16 in CI (#165)

doc/new-development-setup.md
Without quotes around "@folio:registry", this operation fails on Windows (PowerShell).  
Instead of creating the expected config line, it creates a config with the URL as the key, 
assigned to 'true'.
```
PS> yarn config list
yarn config v1.22.19
info yarn config
{
...
'https://repository.folio.org/repository/npm-folio/': true,
...
}
```
With the quotes, the config statement works as expected.
=> Add quotes around "@folio:registry"

CHANGELOG.md, package.json
_Actually update_ the minor versions of the constituent stripes-* packages. The [7.3.0 release](https://github.com/folio-org/stripes/releases/tag/v7.3.0) left them at their 7.2.0 versions 😬 , despite what the changelog claimed.
=> Release v7.3.1

package.json, ui/index.js
https://issues.folio.org/browse/STRIPES-820
Add `stripes-ui` as a dependency.
The other PRs related to this are:
https://github.com/folio-org/stripes-core/pull/1256
https://github.com/folio-org/stripes-webpack/pull/80
=> STRIPES-820: Add stripes-ui as a dependency

CHANGELOG.md, package.json
Bump the major version to 8.0.0 to reflect incoming breaking changes in stripes-components, stripes-core, and possibly stripes-smart-components.
=> bump major version to 8.0

CHANGELOG.md, package.json
- Fulfills [STRIPES-834](https://issues.folio.org/browse/STRIPES-834)
- Updated `react-redux` to `v8`
- Updated `stripes-connect` to `8.1.0`
=> STRIPES-834 Update react-redux, stripes-connect

CHANGELOG.md, package.json
https://issues.folio.org/browse/STRIPES-860
Bump redux to ^4.2.1 to align with what will be installed on the platform: https://github.com/folio-org/platform-complete/pull/2407
=> STRIPES-860: Bump redux to ^4.2.1

CHANGELOG.md, package.json
Upgrade `react` to `v18`, and all `@folio/stripes-*` dependencies accordingly.
Refs [STRIPES-872](https://issues.folio.org/browse/STRIPES-872)
=> STRIPES-872 BREAKING react 18

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
In CI, bump NodeJS from v16 to v18.
Refs [STRIPES-881](https://issues.folio.org/browse/STRIPES-881)
=> STRIPES-881 use NodeJS v18 in CI

.eslintrc, CHANGELOG.md, README.md, components/index.d.ts, core/index.d.ts, final-form/index.d.ts, package.json, smart-components/index.d.ts
=> Re-export type declarations from stripes-types

package.json
Align the `react-redux` dependency constraint across `@folio/stripes` and `platform-complete`. Mismatched constraints cause build warnings in the parent package like 
```
warning " > @folio/stripes@9.1.100000303" has incorrect peer dependency "react-redux@~8.0.5".
```
Refs [STRIPES-894](https://issues.folio.org/browse/STRIPES-894)
=> STRIPES-894 loosen react-redux to mitigate install warning

CHANGELOG.md, package.json
Includes [stripes-components v12.0.5](https://github.com/folio-org/stripes-components/releases/tag/v12.0.5)
=> Release v9.0.5

.github/workflows/ui.yml
There is no module descriptor here. Additionally, make this workflow conditional to avoid running twice when GA logs multiple events for the same action when opening a new PR.
Refs [STRIPES-939](https://folio-org.atlassian.net/browse/STRIPES-939), [STRIPES-938](https://folio-org.atlassian.net/browse/STRIPES-938)
=> STRIPES-939 GA: omit publishing MD

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
GithHub deprecated v2; use v4 instead.
=> bump workflow's upload-artifact action to v4

CHANGELOG.md, package.json
Includes `stripes-components` v13,0.6:
- Bugfix - clicking the trigger on an open <Popover> now closes the <Popover> instead of closing/reopening. Refs STCOM-1429.
=> Release v10.0.10
